### ISSUE TITLE
Support Graphene like filtering

### ISSUE THREAD

**Issue by phortx** [vuex-orm/plugin-graphql#48]
Python Graphene does filtering like this:

```graphql
query {
  # Note that fields names become camelcased
  allAnimals(genus: "cat", name_Icontains: "lion") {
    edges {
      node {
        id,
        name
      }
    }
  }
}
```

I think we should support that too as an alternative to the FilterType based filtering

**Comment by collab0** [comment]
Hey, any updates on this? :+1:

**Comment by phortx** [comment]
Currently not, but I'm open for Pull Requests here :)

**Comment by gotexis** [comment]
@phortx 

I am just starting with this plugin and I saw your post. Pretty sure I will be wanting the same thing with you.

Did you get this achieved? What is the barrier? Let me see what I can do.

**Comment by phortx** [comment]
There is no barrier, I just don't have any time for this project currently :(

I'm open for PRs regarding this.

**Comment by gotexis** [comment]
@phortx 
I have little knowledge of typescript, but I looked at which code needs to be changed (at least for me, since I can't edit the source code, I need to figure out how to manually do a query):

in vuex-orm-graphql.ts, line 57:

```ts
    (context.components.Model as typeof PatchedModel).fetch = async function(
      filter: any,
      bypassCache = false
    ) {
      let filterObj = filter;
      if (!isPlainObject(filterObj)) filterObj = { id: filter };
      return this.dispatch("fetch", { filter: filterObj, bypassCache });  // <- this seems how the filter is constructed
    };
```

So, I wonder if below is gonna work, for example the model's name is `Product`

```es
Product.dispatch("fetch", { id: 1})
```

**Comment by phortx** [comment]
@gotexis Thank you very much for making progress on this and the code proposals.

Actually I would like to change the way the `filter` argument is processed. IMHO the API of this plugin should be unaffected by the design of the GraphQL Schema.

I want to avoid introducing an additional param like `additionalArgs`.

**Comment by gotexis** [comment]
@phortx 
I believe extensibility would be a much valuable specification for a package like this, and that could be achieved with an object-oriented pattern - again, it's just my 2 cents.

I mainly develop on Python, so I do happen to use Graphene/Django. Surely I have lost count of how many hindrances I have encountered with the current stack `Vue/Apollo/Graphene`, and thought of switching to Node-based solution many times, yet now I am still using it, I think mainly because it's Python which is much sleekier than JS.

I guess people who love the Python stack love them because of their object-oriented interface, that (ideally) everything would be a class, so it is easier to modify things just by subclassing, or dropping-in replacements.

Surely a similar style can be implemented for TS, but I could only write Python, so for example, in Python, the code would be like this:

```python

def to_gql(model, args):
    # here we need to have some method to convert model into gql query

class ApolloLink:
    # wrap apollo in a class, like we said in another thread, user could supply their own Apollo link instance
    endpoint_style = "graphene"
    uri = 'http://127.0.0.1'
    # etc...

class QueryBuilder:
    
    apollo_link_class = ApolloLink   # need a machanism to pass global ApolloLink instance 

    def __init__(self, link):
        self.query_style = self.apollo_link_class.endpoint_style

    def build(self, model, filter):   # pass filter as a python dict
        if self.query_style == "graphene":
            query = to_gql(model, args=filter)
        elif self.query_style == "apollo_server" or True:   # any other styles
            query = to_gql(model, args={'filter': filter})
        return 

class Fetcher:  
    # this method would be bound to Vuex-ORM model, just like other methods (filter / mutate )
    builder = QueryBuilder   # the default builder, the user could write or supply a custom one.
    
    def __init__(self, link):
        self.apollo_link = ApolloLink()

    def fetch(self, model, filter):
        query = self.builder.build(model, filter)
        # do fetching command here ...
        

```

**Comment by phortx** [comment]
> plugin has opinion on naming conventions

This is something which will be changed in the future. There will be a NameGenerator class or something which you can overwrite to change how the mutation or query names are generated.

>  Instead of hardcoding graphene as a style, it would be better that user can supply their own QueryBuilder and pluralizer.

This is an interesting idea. I think we could easily allow overwriting the QueryBuilder, the NameGenerator and other parts of the plugin.

> I guess people who love the Python stack love them because of their object-oriented interface, that (ideally) everything would be a class, so it is easier to modify things just by subclassing, or dropping-in replacements.

Absolutely. However remember, that this is a plugin for Vuex-ORM which is based on Vuex. And thus we're somewhat tied to the way these both libraries work ;)

**Comment by phortx** [comment]
https://github.com/vuex-orm/plugin-graphql/pull/89 should introduce everything we need here, I think :)

**Comment by phortx** [comment]
Merged (but not released yet).
