### ISSUE TITLE
Non integer id broken with mutation

### ISSUE THREAD

**Issue by mkaay** [vuex-orm/plugin-graphql#62]
If a mutation returns a non integer id (like a relay node), a new record with id NaN is created.
I found this while debugging:
https://github.com/vuex-orm/plugin-graphql/blob/0730a86e8efa4e584312c49bd7d5a3eb54ba5fb0/src/actions/action.ts#L44
Something like this might be better:
```
const newId = Number.parseInt(newData.id, 10);
if (!Number.isNaN(newId)) {
    newData.id = newId;
}
```

**Comment by phortx** [comment]
Thanks for this issue, Marius,

The problem here is, that Vuex-ORM only supports integer IDs as far as I know and thus this plugin expects integer IDs too.

@kiaking Can you say something about the state of non-integer IDs for Vuex-ORM records? I think there was some issue when not using `increment` type as ID.

**Comment by kiaking** [comment]
@phortx Vuex ORM don't have any limitation on the value of ID (value of primary key). it can be string or number. or even null or boolean as well (you don't think you should though).

So I think there's no problem storing the id value as string. In fact, Vuex ORM will convert the primary key value to string if it's number for the key of the state.

For example;

```js
// If you save this data.
const data = {
  id: 1 // <- Number
}

// It becomes like this inside the state.
{
  '1': { // <- Key is the ID value and it's always string.
    id: 1
  }
}
```

If the ID value is string, it becomes like this.

```js
const data = {
  id: 'string-id-001'
}

// Inside state.
{
  'string-id-001': {
    id: 'string-id-001'
  }
}
```  

You are correct about `this.increment()` attribute only supports number (because otherwise string can't be "incremented"). But other than `this.increment()`,  it's completely OK to pass string as a value.

**Comment by phortx** [comment]
Ok, that sounds good. Thanks for the reply!

I will try to move to string based IDs soon, however PRs are welcome :)

**Comment by fardarter** [comment]
@kiaking I was successfully using string based ids until I had to set up a pivot table. It sets up fine with ints but not strings.

Will be digging into it more this weekend. Hopefully I'm wrong.

I want ID overwrites for some of them. It's a series of defined roles; enumeration.

**Comment by phortx** [comment]
I've setup a PR to make this pluggin support string based IDs. And all tests pass except the ones for hasManyThrough (pivot table) relations. I think there might by a bug in the core :)

**Comment by phortx** [comment]
Should be working with the next release.
