### ISSUE TITLE
Documentation for quick start

### ISSUE THREAD

**Issue by gotexis** [vuex-orm/plugin-graphql#79]
Hey, I really like what this project is trying to achieve. This project may be my lifesaver since 2019... I would gladly contribute to this project in any way 

So that I could have a try, could I ask for a more complete start-from-scratch / demo setup guide?

As per https://vuex-orm.github.io/vuex-orm/guide/prologue/getting-started.html#creating-data-to-vuex-store, the document declares
```javascript
import User from 'data/models/user';
```

Then you can probably do shit for the user model, like 

```js
destroy(user)
users: () => User.query().withAll().all()
```

Yet I have zero idea WTF is / what to expect / what to put in that file...

I understand probably have to use with https://vuex-orm.github.io/vuex-orm/guide/prologue/getting-started.html#create-models as well

But maybe what I am asking is just a sample working demo code so I can drag it to my project and batch rename "User" to "Item" (my model name) was...

Yes I may be greedy and lazy but isn't that why this project is here :)

Also, the slack invitation has expired :)

**Comment by phortx** [comment]
Nice to hear that. Basically this plugin is a addition to Vuex-ORM and expects that you already have setup Vuex, Vuex-ORM and model definitions and that you have a understanding of Vuex-ORM.

The goal of this project is not to skip Vuex-ORM and give you start from scratch instructions, due to the fact that missing Vuex/Vuex-ORM knowledge will lead you to errors.

Sorry :)

However a repository with sample API and sample Vue app would be awesome!
